server :
  port:8080

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/dbchemco_hrms
    password : root
    username : root
  jpa :
    show-sql : true
    hibernate :
      ddl-auto : create
    properties :
      hibernate :
        dialect : org.hibernate.dialect.MySql8.Dialect
